In [1]:
import pandas as pd

In [4]:
exp = 'exp16'
unit = 'ldr'
measure = 'occmean'

y_filename = f'./input/{exp}/y_{unit}_{measure}_{exp}.csv'
print(y_filename)

pc_predictions_filename = f'./output/{exp}/pc_predictions_{exp}_long.csv'
print(pc_predictions_filename)

./input/exp16/y_ldr_occmean_exp16.csv
./output/exp16/pc_predictions_exp16_long.csv

In [18]:
y_df = pd.read_csv(y_filename)
y_df.columns = ['scenario', 'simulated']
y_df['unit'] = unit
y_df['measure'] = measure
y_df

    scenario  simulated unit  measure
0          1   1.543653  ldr  occmean
1          2   1.543653  ldr  occmean
2          3   1.415112  ldr  occmean
3          4   1.543653  ldr  occmean
4          5   1.543653  ldr  occmean
5          6   1.415112  ldr  occmean
6          7   1.676228  ldr  occmean
7          8   1.676228  ldr  occmean
8          9   1.494792  ldr  occmean
9         10   4.535407  ldr  occmean
10        11   4.535407  ldr  occmean
11        12   4.385944  ldr  occmean
12        13   4.535407  ldr  occmean
13        14   4.535407  ldr  occmean
14        15   4.385944  ldr  occmean
15        16   4.760829  ldr  occmean
16        17   4.760829  ldr  occmean
17        18   4.543692  ldr  occmean
18        19   7.507911  ldr  occmean
19        20   7.417439  ldr  occmean
20        21   7.302215  ldr  occmean
21        22   7.696912  ldr  occmean
22        23   7.586410  ldr  occmean
23        24   7.447951  ldr  occmean
24        25   7.965757  ldr  occmean
25        26   7.807031  ldr  occmean
26        27   7.621466  ldr  occmean
27        28  10.549837  ldr  occmean
28        29  10.452767  ldr  occmean
29        30  10.295547  ldr  occmean
30        31  10.698864  ldr  occmean
31        32  10.586508  ldr  occmean
32        33  10.408427  ldr  occmean
33        34  10.931104  ldr  occmean
34        35  10.778774  ldr  occmean
35        36  10.550578  ldr  occmean
36        37  13.444833  ldr  occmean
37        38  13.351623  ldr  occmean
38        39  13.181739  ldr  occmean
39        40  13.613947  ldr  occmean
40        41  13.505914  ldr  occmean
41        42  13.315652  ldr  occmean
42        43  13.934208  ldr  occmean
43        44  13.782886  ldr  occmean
44        45  13.529471  ldr  occmean

In [13]:
predictions_df = pd.read_csv(pc_predictions_filename)
predictions_df

      scenario unit              measure qdata model  prediction
0            1  ldr              occmean     q    lm    1.804039
1            2  ldr              occmean     q    lm    1.804039
2            3  ldr              occmean     q    lm    1.651497
3            4  ldr              occmean     q    lm    1.804039
4            5  ldr              occmean     q    lm    1.804039
...        ...  ...                  ...   ...   ...         ...
6295        41  obs  condmeantimeblocked   noq    nn    3.711717
6296        42  obs  condmeantimeblocked   noq    nn    2.079412
6297        43  obs  condmeantimeblocked   noq    nn    4.137368
6298        44  obs  condmeantimeblocked   noq    nn    3.733185
6299        45  obs  condmeantimeblocked   noq    nn    1.868988

[6300 rows x 6 columns]

In [10]:
predictions_actual_df = predictions_df.merge(y_df, how='left', on=['scenario', 'unit', 'measure'])
predictions_actual_df

,scenario,unit,measure,qdata,model,prediction,occ_mean_mean_ldr
0,1,ldr,occmean,q,lm,1.804039,1.543653
1,2,ldr,occmean,q,lm,1.804039,1.543653
2,3,ldr,occmean,q,lm,1.651497,1.415112
3,4,ldr,occmean,q,lm,1.804039,1.543653
4,5,ldr,occmean,q,lm,1.804039,1.543653
...,...,...,...,...,...,...,...
6295,41,obs,condmeantimeblocked,noq,nn,3.711717,NaN
6296,42,obs,condmeantimeblocked,noq,nn,2.079412,NaN
6297,43,obs,condmeantimeblocked,noq,nn,4.137368,NaN
6298,44,obs,condmeantimeblocked,noq,nn,3.733185,NaN
6299,45,obs,condmeantimeblocked,noq,nn,1.868988,NaN

In [2]:
exp = 'exp16'

unit_measure_pairs = [('ldr', 'occmean'), ('ldr', 'occp95'), ('ldr', 'probblocked'), ('ldr', 'condmeantimeblocked'),
                     ('obs', 'occmean'), ('obs', 'occp95'), ('obs', 'probblocked'), ('obs', 'condmeantimeblocked'),
                     ('pp', 'occmean'), ('pp', 'occp95')]

In [5]:
pc_predictions_filename = f'./output/{exp}/pc_predictions_{exp}_long.csv'
predictions_df = pd.read_csv(pc_predictions_filename)

predictions_simulated_filename = f'./output/{exp}/predictions_simulated_{exp}_long.csv'

y_dfs = []
for (unit, measure) in unit_measure_pairs:
    y_filename = f'./input/{exp}/y_{unit}_{measure}_{exp}.csv'
    y_df = pd.read_csv(y_filename)
    y_df.columns = ['scenario', 'simulated']
    y_df['unit'] = unit
    y_df['measure'] = measure
    y_dfs.append(y_df)
    
simulated_df = pd.concat(y_dfs)
    
# Merge in actual values with predictions
predictions_simulated_df = predictions_df.merge(simulated_df, how='left', on=['scenario', 'unit', 'measure'])
    
predictions_simulated_df.to_csv(predictions_simulated_filename, index=False)